apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: camel-quarkus-rest
  namespace: default
spec:
  template:
    metadata:
      name: camel-quarkus-rest-v1
    spec:
      containers:
        - image: __IMAGE__
  traffic:
    - tag: latest
      latestRevision: true
      percent: 100