# Here we specify the input github repo
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-camel-talk
  namespace: ci-pipeline
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/omarsmak/camel-talk-examples
---
## This is only needed to pump up the repo memory since graalvm native image is very memory intensive
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: ci-pipeline
spec:
  limits:
    - max:
        memory: "6Gi"
      type: Container
---
# This is our task blueprint, here we define the steps needed to happen but we didn't yet run the task
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: camel-quarkus-rest-task
  namespace: ci-pipeline
spec:
  inputs:
    resources:
      - name: git-source-camel-talk
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
      - name: imageUrl
        description: Url of image repository
      - name: imageTag
        description: Tag to apply to the built image
        default: "latest"
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
  steps:
#    - name: build-and-push
#      image: gcr.io/kaniko-project/executor:v0.15.0
#      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
#      env:
#        - name: "DOCKER_CONFIG"
#          value: "/tekton/home/.docker/"
#      command:
#        - /kaniko/executor
#      args:
#        - --dockerfile=$(inputs.params.pathToDockerFile)
#        - --destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)
#        - --context=$(inputs.params.pathToContext)
    - name: deploy
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
        - "$(inputs.params.pathToYamlFile)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.params.pathToYamlFile)"
---